spring:
  messages:
    basename: static/i18n/message #相对路径 开头请勿添加斜杠
  datasource:
      # 数据源基本配置
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jdbc11
      type: com.alibaba.druid.pool.DruidDataSource
      #  数据源其他配置
      druid:
          initial-size: 5
          min-idle: 5
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          use-global-data-source-stat: true
          connect-properties:  druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall
          web-stat-filter:
              enabled: true
              url-pattern: /*
              #设置不统计哪些URL
              exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
              session-stat-enable: true
              session-stat-max-count: 100
          stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
              reset-enable: true
              #设置监控页面的登录名和密码
              login-username: admin
              login-password: 123456
              allow: 127.0.0.1  #白名单
              deny: 192.168.1.100 #黑名单
#      hikari:
#        auto-commit: true
#        connection-timeout: 30001
#        maximum-pool-size: 100
#        read-only: false
#      type: com.alibaba.druid.pool.DruidDataSource

#  mvc:
#    date-format: yyyy-MM-dd HH:mm:ss
##主文件
#spring:
#  profiles:
#    active: test
#---  #文件分隔符
#server:
#  servlet:
#    context-path: /dev
#spring:
#  profiles: dev  #环境名 或 文件名
#
#---
#server:
#  servlet:
#    context-path: /prod
#spring:
#  profiles: prod  #环境名 或 文件名
#
#---
#server:
#  servlet:
#    context-path: /test
#spring:
#  profiles: test  #环境名 或 文件名